sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t burnsmarty/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true burnsmarty/react-test npm run test

after_success:
  - docker build -t burnsmarty/multi-client ./client
  - docker build -t burnsmarty/multi-nginx ./nginx
  - docker build -t burnsmarty/multi-server ./server
  - docker build -t burnsmarty/multi-worker ./worker
  # login to dockerhub and push images - test with pat
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push burnsmarty/multi-client
  - docker push burnsmarty/multi-nginx
  - docker push burnsmarty/multi-server
  - docker push burnsmarty/multi-worker
